# data_generation.py

import networkx as nx
import pandas as pd
import numpy as np 
import random
from datetime import datetime, timedelta
from gan_model import GANModel
import networkx as nx
from faker import Faker

class GraphWrapper:
    def __init__(self, graph):
        self.graph = graph

    def generate(self, num_samples):
        # Implement the logic to generate synthetic data using the graph
        # Replace this with your actual implementation
        return f"Generated {num_samples} samples using the graph."

def create_healthcare_knowledge_graph(disease_select, genetic_variants):
    # Create a DiGraph (or any other graph structure)
    G = nx.DiGraph()
    # Add nodes and edges based on disease_select and genetic_variants
    # ...
    return GraphWrapper(G)  # Wrap the graph in the GraphWrapper

def apply_semantic_rules(patient_data, params):
    facts = {}
    genetic_variant = patient_data.get('Genetic_Variant')

    # Define risk levels based on genetic variants
    high_risk_variants = ['BRCA1', 'BRCA2', 'TP53', 'ATM', 'MLH1']  # Fewer high-risk variants
    medium_risk_variants = ['KRAS', 'EGFR', 'MSH2', 'MSH6', 'PALB2', 'CHEK2']  # More medium-risk variants
    low_risk_variants = ['NBN', 'RAD51C', 'RAD51D', 'BRIP1', 'PTEN', 'CDH1', 'STK11', 'NF1', 'BAP1', 'GREM1', 'TSC1', 'TSC2', 'VHL', 'RET', 'JAK2', 'BRAF', 'AKT1', 'HER2', 'FGFR1', 'FGFR2', 'FGFR3']  # Low-risk variants

    if genetic_variant in high_risk_variants:
        facts['Disease_Risk'] = 'High Risk'
    elif genetic_variant in medium_risk_variants:
        facts['Disease_Risk'] = 'Medium Risk'
    elif genetic_variant in low_risk_variants:
        facts['Disease_Risk'] = 'Low Risk'
    else:
        facts['Disease_Risk'] = 'Unknown Risk'  # In case the variant is not recognized

    return facts

def generate_synthetic_data(num_samples, G, best_params):
    # Ensure G has a method to generate data
    if hasattr(G, 'generate'):
        synthetic_data = G.generate(num_samples)  # Generate data using G
    else:
        raise AttributeError("The object G does not have a 'generate' method.")

    # Debugging: Check the type of synthetic_data
    print(f"Type of data generated by G: {type(synthetic_data)}")  # Debugging line

    # Ensure the generated data is a NumPy array
    if not isinstance(synthetic_data, np.ndarray):
        raise TypeError("The generated data is not a NumPy array.")

    # Reshape the data if necessary
    try:
        synthetic_data_flat = synthetic_data.reshape(num_samples, -1)  # Reshape to (num_samples, flattened image size)
    except Exception as e:
        raise ValueError(f"Failed to reshape synthetic data: {e}")

    return synthetic_data_flat

def evaluate_data_accuracy(synthetic_data):
    accuracy = np.random.uniform(0.5, 1.0)
    return accuracy

def fitness_function(params, num_samples, G):
    """
    Evaluates the quality of generated synthetic data based on multiple criteria
    Returns a fitness score between 0 and 1
    """
    try:
        # Generate synthetic data
        synthetic_data = generate_synthetic_data(num_samples, G, params)
        
        # Initialize weights for different components
        weights = {
            'age_correlation': 0.25,
            'feature_consistency': 0.25,
            'disease_distribution': 0.25,
            'risk_correlation': 0.25
        }
        
        scores = {}
        
        # 1. Age-Disease Correlation Score
        scores['age_correlation'] = evaluate_age_correlation(synthetic_data)
        
        # 2. Feature Consistency Score
        scores['feature_consistency'] = evaluate_feature_consistency(synthetic_data)
        
        # 3. Disease Distribution Score
        scores['disease_distribution'] = evaluate_disease_distribution(synthetic_data)
        
        # 4. Risk Factor Correlation Score
        scores['risk_correlation'] = evaluate_risk_correlation(synthetic_data)
        
        # Calculate weighted fitness score
        fitness = sum(scores[key] * weights[key] for key in weights.keys())
        
        return fitness

    except Exception as e:
        print(f"Error in fitness calculation: {e}")
        return 0.0

def evaluate_age_correlation(data):
    """Evaluates if age distributions match expected patterns for each disease"""
    try:
        correct_ages = 0
        total_cases = len(data)
        
        for _, row in data.iterrows():
            disease = row['Rare_Disease']
            age = row['Age']
            age_of_onset = row['Age_of_Onset']
            
            # Check if age is appropriate for the disease
            if age >= age_of_onset and age <= age_of_onset + 50:
                correct_ages += 1
                
        return correct_ages / total_cases
    except:
        return 0.5

def evaluate_feature_consistency(data):
    """Evaluates if disease features are consistent with medical knowledge"""
    try:
        consistent_features = 0
        total_features = 0
        
        for _, row in data.iterrows():
            disease = row['Rare_Disease']
            features = set(row['Features'].split(', '))
            expected_features = set(disease_features.get(disease, []))
            
            if features.issubset(expected_features):
                consistent_features += len(features)
            total_features += len(features)
            
        return consistent_features / total_features if total_features > 0 else 0.5
    except:
        return 0.5

def evaluate_disease_distribution(data):
    """Evaluates if disease distribution is balanced"""
    try:
        disease_counts = data['Rare_Disease'].value_counts()
        expected_count = len(data) / len(data['Rare_Disease'].unique())
        
        # Calculate deviation from uniform distribution
        deviation = 1 - (abs(disease_counts - expected_count).mean() / expected_count)
        return max(0, deviation)
    except:
        return 0.5

def evaluate_risk_correlation(data):
    """Evaluates if risk factors correlate with severity and age"""
    try:
        # Calculate correlation between Risk_Factor and other metrics
        risk_age_corr = data['Risk_Factor'].corr(data['Age'])
        risk_severity_corr = data['Risk_Factor'].corr(data['Severity_Score'])
        
        # Average the correlations (should be positive)
        return (abs(risk_age_corr) + abs(risk_severity_corr)) / 2
    except:
        return 0.5

# Parameters
noise_dim = 100  # Dimension of the noise vector
img_shape = (28, 28, 1)  # Shape of the generated images (e.g., for MNIST)

# Initialize the GAN model
G = GANModel(noise_dim, img_shape)

def evolutionary_algorithm(num_generations, population_size, num_samples, G):
    population = []  # Initialize your population
    fitness_scores = [fitness_function(params, num_samples, G) for params in population]

def initialize_random_params():
    # Initialize parameters randomly
    return {
        'weight_range': random.uniform(0.1, 1.0),
        'risk_threshold': random.uniform(0.1, 0.9)
    }

def crossover(parent1, parent2):
    # Implement crossover logic
    child = {}
    for key in parent1.keys():
        child[key] = random.choice([parent1[key], parent2[key]])
    return child

def mutate(params):
    # Implement mutation logic
    if random.random() < 0.1:  # 10% chance to mutate
        params['weight_range'] += random.uniform(-0.05, 0.05)
        params['risk_threshold'] += random.uniform(-0.05, 0.05)

def select_best_individuals(population, fitness_scores, num_selected=10):
    individuals = list(zip(population, fitness_scores))
    individuals.sort(key=lambda x: x[1], reverse=True)
    selected_individuals = [ind[0] for ind in individuals[:num_selected]]
    return selected_individuals

def generate_healthcare_dataset(num_samples=100, selected_diseases=None, selected_variants=None):
    fake = Faker()
    
    # Use selected diseases and variants if provided, otherwise use defaults
    if selected_diseases is None:
        selected_diseases = ['Huntington Disease', 'Cystic Fibrosis', 'Duchenne Muscular Dystrophy',
                         'Tay-Sachs Disease', 'Fabry Disease', 'Gaucher Disease', 
                         'Pompe Disease', 'Niemann-Pick Disease', 'Wilson Disease', 'Marfan Syndrome']
    
    if selected_variants is None:
        selected_variants = ['M1: BRCA1', 'M2: BRCA2', 'M3: TP53', 'M4: PTEN', 'M5: MLH1', 
                           'M6: MSH2', 'M7: APC', 'M8: PALB2', 'M9: ATM', 'M10: CHEK2']

    # Disease-specific features mapping
    disease_features = {
        'Cystic Fibrosis': ['Respiratory Issues', 'Digestive Problems', 'Growth Issues', 'Frequent Lung Infections', 'Salty Skin', 'Poor Weight Gain', 'Breathing Difficulties'],
        'Huntington\'s Disease': ['Neurological Symptoms', 'Cognitive Decline', 'Mood Changes', 'Muscle Problems', 'Balance Issues', 'Speech Difficulties', 'Memory Loss'],
        'Sickle Cell Anemia': ['Chronic Pain', 'Fatigue', 'Frequent Infections', 'Vision Problems', 'Delayed Growth', 'Anemia', 'Joint Pain'],
        'Duchenne Muscular Dystrophy': ['Muscle Weakness', 'Growth Abnormalities', 'Skeletal Deformities', 'Walking Difficulties', 'Frequent Falls', 'Learning Disabilities', 'Heart Problems'],
        'Hemophilia': ['Easy Bruising', 'Prolonged Bleeding', 'Joint Pain', 'Internal Bleeding', 'Nose Bleeds', 'Blood in Urine', 'Muscle Weakness'],
        'Alport Syndrome': ['Kidney Problems', 'Hearing Loss', 'Vision Issues', 'Blood in Urine', 'High Blood Pressure', 'Swelling', 'Fatigue'],
        'Amyotrophic Lateral Sclerosis (ALS)': ['Muscle Weakness', 'Speech Problems', 'Difficulty Swallowing', 'Breathing Problems', 'Muscle Cramping', 'Balance Issues', 'Weight Loss'],
        'Angelman Syndrome': ['Development Delay', 'Speech Impairment', 'Balance Problems', 'Seizures', 'Sleep Issues', 'Happy Demeanor', 'Hand Flapping'],
        'Ataxia-Telangiectasia': ['Balance Problems', 'Eye Movement Issues', 'Immune System Problems', 'Frequent Infections', 'Movement Difficulties', 'Spider Veins', 'Growth Issues'],
        'Bardet-Biedl Syndrome': ['Vision Loss', 'Obesity', 'Extra Fingers/Toes', 'Kidney Problems', 'Learning Difficulties', 'Coordination Problems', 'Delayed Development'],
        'Batten Disease': ['Vision Loss', 'Seizures', 'Cognitive Decline', 'Motor Skills Loss', 'Speech Problems', 'Behavioral Changes', 'Sleep Issues'],
        'Churg-Strauss Syndrome': ['Asthma', 'Allergies', 'Blood Vessel Inflammation', 'Nerve Pain', 'Skin Changes', 'Sinus Problems', 'Weight Loss'],
        'Cystinosis': ['Kidney Problems', 'Growth Issues', 'Light Sensitivity', 'Muscle Weakness', 'Thyroid Issues', 'Dehydration', 'Crystals in Eyes'],
        'Ehlers-Danlos Syndrome': ['Joint Hypermobility', 'Skin Elasticity', 'Easy Bruising', 'Chronic Pain', 'Digestive Issues', 'Dislocation Risk', 'Poor Wound Healing'],
        'Fabry Disease': ['Organ Failure', 'Pain Symptoms', 'Skin Problems', 'Kidney Issues', 'Heart Complications', 'Gastrointestinal Issues', 'Heat Intolerance'],
        'Gaucher Disease': ['Organ Enlargement', 'Bone Problems', 'Blood Disorders', 'Fatigue', 'Growth Delay', 'Joint Pain', 'Bleeding Issues'],
        'Kawasaki Disease': ['High Fever', 'Rash', 'Swollen Lymph Nodes', 'Red Eyes', 'Lips and Tongue Changes', 'Joint Pain', 'Heart Complications'],
        'Marfan Syndrome': ['Skeletal Deformities', 'Heart Problems', 'Vision Issues', 'Long Limbs', 'Flexible Joints', 'Aortic Enlargement', 'Chest Abnormalities'],
        'Menkes Disease': ['Developmental Delay', 'Weak Muscle Tone', 'Seizures', 'Abnormal Hair', 'Temperature Instability', 'Feeding Difficulties', 'Growth Failure'],
        'Neimann-Pick Disease': ['Neurological Symptoms', 'Organ Enlargement', 'Development Issues', 'Balance Problems', 'Speech Difficulties', 'Liver Problems', 'Learning Disabilities'],
        'Osteogenesis Imperfecta': ['Brittle Bones', 'Blue Sclera', 'Short Stature', 'Hearing Loss', 'Easily Broken Bones', 'Curved Spine', 'Joint Laxity'],
        'Phenylketonuria (PKU)': ['Intellectual Disability', 'Behavioral Problems', 'Seizures', 'Skin Problems', 'Growth Issues', 'Head Size Abnormalities', 'Hyperactivity'],
        'Prader-Willi Syndrome': ['Low Muscle Tone', 'Excessive Hunger', 'Developmental Delays', 'Behavioral Problems', 'Short Stature', 'Sleep Issues', 'Learning Difficulties'],
        'Rett Syndrome': ['Loss of Speech', 'Hand Movement Loss', 'Growth Delay', 'Breathing Problems', 'Seizures', 'Scoliosis', 'Sleep Disturbances'],
        'Wilson\'s Disease': ['Liver Problems', 'Neurological Symptoms', 'Behavioral Changes', 'Speech Problems', 'Tremors', 'Muscle Stiffness', 'Psychiatric Issues']
    }

    # Disease-specific age of onset ranges
    age_onset_ranges = {
        'Cystic Fibrosis': (0, 5),
        'Huntington\'s Disease': (30, 50),
        'Sickle Cell Anemia': (0, 5),
        'Duchenne Muscular Dystrophy': (3, 7),
        'Hemophilia': (0, 2),
        'Alport Syndrome': (5, 15),
        'Amyotrophic Lateral Sclerosis (ALS)': (40, 70),
        'Angelman Syndrome': (0, 3),
        'Ataxia-Telangiectasia': (1, 4),
        'Bardet-Biedl Syndrome': (0, 5),
        'Batten Disease': (4, 10),
        'Churg-Strauss Syndrome': (30, 50),
        'Cystinosis': (0, 2),
        'Ehlers-Danlos Syndrome': (5, 15),
        'Fabry Disease': (5, 10),
        'Gaucher Disease': (0, 20),
        'Kawasaki Disease': (0, 5),
        'Marfan Syndrome': (5, 20),
        'Menkes Disease': (0, 1),
        'Neimann-Pick Disease': (0, 3),
        'Osteogenesis Imperfecta': (0, 1),
        'Phenylketonuria (PKU)': (0, 1),
        'Prader-Willi Syndrome': (0, 1),
        'Rett Syndrome': (6, 18),
        'Wilson\'s Disease': (5, 35)
    }

    data = {
        'Sr': range(1, num_samples + 1),
        'Name': [fake.name() for _ in range(num_samples)],
        'Age': [],
        'Mutation': [],
        'Rare_Disease': [],
        'Features': [],
        'Death_Rate': [],
        'Severity_Score': [],
        'Age_of_Onset': [],
        'Family_History': [],
        'Treatment_Response': []
    }

    for i in range(num_samples):
        # Select disease and variant
        disease = random.choice(selected_diseases)
        variant = random.choice(selected_variants)
        
        # Get disease-specific features
        disease_specific_features = disease_features.get(disease, ['Unknown'])
        
        # Get age of onset range for the disease
        onset_min, onset_max = age_onset_ranges.get(disease, (0, 70))
        age_of_onset = random.randint(onset_min, onset_max)
        
        # Calculate appropriate age based on age of onset
        min_age = max(age_of_onset, 1)
        max_age = min(age_of_onset + 50, 90)
        age = random.randint(min_age, max_age)

        # Generate severity score based on age and onset
        base_severity = random.randint(1, 10)
        if age - age_of_onset > 20:
            severity = min(10, base_severity + 2)
        else:
            severity = base_severity

        # Calculate death rate based on severity and age
        death_rate = round(min(0.9, (severity/10 + (age-age_of_onset)/100)), 2)

        # Append data
        data['Age'].append(age)
        data['Mutation'].append(variant)
        data['Rare_Disease'].append(disease)
        data['Features'].append(', '.join(random.sample(disease_specific_features, 
                                                       random.randint(1, len(disease_specific_features)))))
        data['Death_Rate'].append(death_rate)
        data['Severity_Score'].append(severity)
        data['Age_of_Onset'].append(age_of_onset)
        data['Family_History'].append(random.choice(['Yes', 'No']))
        data['Treatment_Response'].append(random.choice(['Positive', 'Negative', 'Neutral']))
    
    df = pd.DataFrame(data)
    
    # Add calculated field for Risk Factor
    df['Risk_Factor'] = df.apply(lambda row: calculate_risk_factor(row), axis=1)
    
    return df

def calculate_risk_factor(row):
    """Calculate risk factor based on multiple parameters"""
    base_risk = 0
    
    # Age factor
    if row['Age'] > 60:
        base_risk += 3
    elif row['Age'] > 40:
        base_risk += 2
    elif row['Age'] > 20:
        base_risk += 1
        
    # Death rate factor
    base_risk += int(row['Death_Rate'] * 5)
    
    # Severity factor
    base_risk += row['Severity_Score'] // 2
    
    # Family history factor
    if row['Family_History'] == 'Yes':
        base_risk += 2
        
    # Normalize risk factor to 1-10 scale
    risk_factor = min(10, max(1, base_risk))
    
    return risk_factor

# Example usage:
if __name__ == "__main__":
    # Generate sample dataset
    df = generate_healthcare_dataset(100)
    
    # Save to CSV
    df.to_csv('healthcare_dataset.csv', index=False)
    
    # Display first few rows
    print(df.head())
